name: 'C++ CI (Conan)'

on:
  push:
    branches:
      - master
      - feature/github_actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install system requirements
        run: sudo apt-get update && sudo apt-get install cmake python3-pip python3-venv build-essential -y

      - name: Install pipx
        run: sudo apt-get install pipx -y && pipx ensurepath

      - name: Install Conan
        run: pipx install conan

      - name: Conan profile detect
        run: conan profile detect --force

      - name: Conan install
        run: conan install . --output-folder=build --build=missing

      - name: CMake configure
        run: cmake -B build -DPATCH_VERSION=${{ github.run_number }} -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: cmake --build build --target package

      - name: Show build folder contents
        run: ls -l build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GIT
